---
title: Daybreak Church
timezone: America/Los_Angeles
collections:
  communicators:
    title: Communicators
    output: false
  events:
    title: Events
    output: true
  messages:
    title: Messages
    output: true
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  series:
    title: Series
    output: true
  staff:
    title: Staff
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event_details
    custom_dates: 
    location: 
    external_url: 
    video_embed: 
    non_header_video_embed: 
    image: 
    small_image: 
    meta_text: 
    primary_button:
      label: 
      link: 
    seconday_buttons:
    - label: 
      link: 
- scope:
    path: ''
    type: messages
  values:
    layout: message
    series: 
    communicator: 
    youtube_id: 
- scope:
    path: ''
    type: series
  values:
    layout: series
    image: 
    small_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: single_item
    is_in_top_nav: false
    video_embed: 
    non_header_video_embed: 
    image: 
    header_bg_image: 
    header_bg_unsplash_id: 
    meta_text: 
    primary_button:
      label: 
      link: 
    seconday_buttons:
    - label: 
      link: 
- scope:
    path: ''
    type: sections
  values:
    is_in_subnav: true
    template: 
- scope:
    path: ''
    type: staff
  values:
    job_title: 
    email: 
    image: 
footer_nav:
- label: About
  link: "/about"
  sub_links:
  - label: New to Daybreak?
    link: "/new-to-daybreak"
  - label: Our Beliefs
    link: "/about/#our-beliefs"
  - label: Staff
    link: "/about/#staff"
  - label: Jobs
    link: "/about/#jobs"
  - label: Missions
    link: "/about/#missions"
  - label: Contact Us
    link: "/contact"
- label: Kids & Students
  link: "/kids-and-students"
  sub_links:
  - label: Kids
    link: "/kids-and-students/#kids"
  - label: Students
    link: "/kids-and-students/#students"
  - label: Young Adults
    link: "/kids-and-students/#young-adults"
- label: Events
  link: "/events"
  sub_links:
  - label: Upcoming Events
    link: "/events"
  - label: Groups
    link: "/events/#groups"
- label: Next Steps
  link: "/next-steps"
  sub_links:
  - label: Taking the Next Step
    link: "/next-steps/#taking-the-next-step"
  - label: Life Groups
    link: "/next-steps/#life-groups"
  - label: Daybreak Leadership College
    link: "/next-steps/#daybreak-leadership-college"
  - label: Prayer Requests
    link: "/next-steps/#prayer-requests"
- label: Give
  link: "/give"
- label: Messages
  link: "/messages"
future: true
description: Carlsbad, California based Christian Church.
baseurl: 
url: http://daybreakchurch.org
facebook_username: daybreakchurch
instagram_username: daybreak.church
google_analytics: UA-35147736-1
markdown: kramdown
permalink: pretty
sass:
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- bin
- Rakefile
- vendor/bootstrap/
homepage:
  title: Indoor Service 9:00a Register in Advance, Outdoor Services 9:00 & 10:00a
    Every Sunday
  subtitle: Watch Online 9:00 & 10:00a
  button:
    label: Click here to watch the online service
    link: https://daybreakca.online.church
address:
  street: 6515 Ambrosia Ln
  city: Carlsbad
  state: CA
  zip: 92011
phone: "(760) 931-7773"
email: info@daybreakchurch.org
service_times:
- Sunday: Indoors 9:00a, Outdoors  9:00, 10:00a  & Online
youth_service_times:
- Birth - kindergarten: Indoors and Online
- 1st - 5th Grade: 'Indoors and Online '
- 6th-8th Grade: Sunday at 6:00-7:30p Indoors
- High School: Sunday at 6:00-7:30p Indoors
- Young Adults: Mondays at 7:00p Indoors
